analyzer:
  errors:
    unused_import: error
    unused_local_variable: error
  exclude:
    - build/**
    - windows/**
    - macos/**
    - linux/**
linter:
  rules:
    - avoid_print
    - cancel_subscriptions
    - close_sinks
    - unawaited_futures
    - use_build_context_synchronously
